### ISSUE TITLE
As a developer, I would like to do local testing without exceptions due to the "registration email feature"

### ISSUE THREAD

**Issue by gr-hovest-atb** [coatrack/coatrack#100]
Whenever I am testing on my local PC and filling in the registration form, I get an exception due to the email server settings not being properly configured. 

We should think about the option of switching off the "send registration emails feature" via a config server setting (or another approach that allows local dev testing without the need of an email server).

**Comment by BrunoSilvaATB** [comment]
This is connected to #140
