### ISSUE TITLE
CoatRack was not able to get user details from GitHub Oauth due to Brownout/deprecation of query param

### ISSUE THREAD

**Issue by BrunoSilvaATB** [coatrack/coatrack#121]
When logging in to CoatRack via Github, the following error occured:
![image](https://user-images.githubusercontent.com/47450617/117942546-742c3b00-b30b-11eb-8e84-3af439c1ddf2.png)
The log said:
![image](https://user-images.githubusercontent.com/6480551/117942879-d4bb7800-b30b-11eb-8dcc-66de2dd0788a.png)
![image](https://user-images.githubusercontent.com/6480551/117942917-e00ea380-b30b-11eb-84f6-de3495f28785.png)

I have found out that this happened due to the Brownouts done by GitHub in order for us developers to have time to update the code to now use query params. Please check the [link](https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/).
On the link above, it is reported that there will be a deprecation of the method used to get user details through a query param and most important, this changes will be finally applied at 8th September, which will cause our Github Oauth to not work properly.

Just as an extra info, this is what I found while debuging our code in master:

![image](https://user-images.githubusercontent.com/47450617/117942860-cec59700-b30b-11eb-90cf-92f52f346244.png)

**Comment by gr-hovest-atb** [comment]
It seems like the relevant config parameter is `security.oauth2.client.authenticationScheme`. After changing the default config from:
``` 
          "security.oauth2.client.authenticationScheme" : "query",

```
to 
``` 
          "security.oauth2.client.authenticationScheme" : "header",
```
it seems to work fine. 

To be further tested.

**Comment by gr-hovest-atb** [comment]
Just a note: It may be that the related parameter: `security.oauth2.client.clientAuthenticationScheme` also needs to be changed, up to now it was `form` but maybe it also needs to be changed to `header`. But this is not directly mentioned in the above linked Github blog post, as `form` does obviously _not_ send client id/secret as query parameter but as form fields.

**Comment by perezdf** [comment]
requested change done

https://bitbucket.org/perezdf/anthill-settings/commits/e72300aa5180c39404f9087e4e1f31e83cf7e88f
