### ISSUE TITLE
Email configuration is not working when registering a new user

### ISSUE THREAD

**Issue by BrunoSilvaATB** [coatrack/coatrack#139]
When registering a new user in CoatRack, there is an error config with the email, thus not allowing the user to login and start using CoatRack.

![email_issue](https://user-images.githubusercontent.com/47450617/129869950-99c3f3e2-9098-47c3-a767-2a38b6488451.png)

**Comment by perezdf** [comment]
I think you are using the default script which contains a empty email user credentials. You must specify your own email account in order to make use of it in your local

**Comment by gr-hovest-atb** [comment]
We need to add instructions to the README and/or wiki, explaining how to configure this when running locally.

Besides, we should think about the option to switch "sending emails" off, which would be relevant especially for local development of new features that are unrelated, see #100
