### ISSUE TITLE
Make the "sender from mail" configurable

### ISSUE THREAD

**Issue by perezdf** [coatrack/coatrack#140]
This is the current code which makes used of coatrack@kyoe.es mail account as initial implementation (or original implementation). However, since we have released and published the project as Open Source project, it is required a more flexible way to parametrize such properties.

I propose to add a new property similar than "ygg.mail.sender.user" as quick solution, but I am open to heard new proposal because the amount of "on fly" properties for building and deployng the app is getting to large (user, password, server url, port...)
```


JavaMailSenderImpl mailSender = new JavaMailSenderImpl();
        mailSender.setHost(mail_server_url);
        mailSender.setPort(mail_server_port);
        mailSender.setProtocol("smtp");

        mailSender.setUsername(mail_sender_user);
        mailSender.setPassword(mail_sender_password);

        Properties props = mailSender.getJavaMailProperties();
        props.put("mail.transport.protocol", "smtp");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.debug", "true");
        props.put("mail.smtp.ssl.enable", "true");
        
        MimeMessage message = mailSender.createMimeMessage();
        MimeMessageHelper helper = new MimeMessageHelper(message, true);
        helper.setTo(user.getEmail());
        helper.setFrom("coatrack@kyoe.es");
        helper.setSubject("Verification of your email address");
        helper.setText("Dear Sir or Madam </p></p></p> In order to verify your email address, please open the following link: </p> <p><a \n"
                + "href=\"" + mail_verification_server_url + "/users/" + user.getId() + "/verify/" + user.getEmailVerifiedUrl() + "\">Verify, please </a></p>\n"
                + "\n"
                + "<p>Best regards</p>\n"
                + "\n"
                + "<p>Coatrack Team</p>", true);
        mailSender.send(message);

        return "redirect:/admin";
```

**Comment by perezdf** [comment]
I have assigned to you all in order to ask for your opinion, on parallel I will do a quick patch in order to fix it as soon as possible

**Comment by gr-hovest-atb** [comment]
I fully agree that this should be configurable. 

However, in general, I am wondering if we should add some of these parameters into the `application.yml` in config server rather than expecting them to be set as environment variables? Maybe we should create a specific section for "mail" properties into our config?

**Comment by BrunoSilvaATB** [comment]
I also agree that the email parameters should be configurable.
I really like @gr-hovest-atb idea, and also one extra parameter that allow for example to disable the email feature on local env.

**Comment by perezdf** [comment]
then, we will add into the application-admin.yml
