### ISSUE TITLE
Easy deployment of CoatRack Web Application via IDE/CLI

### ISSUE THREAD

**Issue by ChristophBaierATB** [coatrack/coatrack#184]
### Context: 
* #177 will ease the process of deploying CoatRack setup for production. 
* However, it is still hard to run CoatRack as a developer because a lot of configurations are to be set previously by hand. #152 will ease the process by providing an out-of-the-box working application.yml for the CoatRack Config Server. It would be nice to have a similar approach for the Web Application. 

### Requirement:
* The Web Application should either be directly runnable from source code using an easy mechanism like a profile or, even better, by just using a default profile so the developer has not to apply any further configurations to start it.

**Comment by gr-hovest-atb** [comment]
The ideal situation would be if a developer could just:

- clone the Github code
- then run a script that builds CoatRack and starts the admin application

The main barrier to reach this goal seems to be that CoatRack currently requires a Git repository to store the gateway configurations at runtime, and such a Git repository is not included in the current setup (it is expected to have it on an external server and put the connection URL/credentials into the `application.yml` of the CoatRack admin web application).

So the first step would be to:

- either find a solution without a Git repository
- or include a Git repository in the CoatRack setup

A script to run CoatRack would then need to include the steps:

- build all CoatRack modules
- start/init Git repo
- startup CoatRack config server
- startup CoatRack admin server

**Comment by ChristophBaierATB** [comment]
We are already getting rid of the external git service within [this branch](https://github.com/BrunoSilvaATB/coatrack/pull/38/files) which solves #167. This can be used as a base branch for solving this issue.

**Comment by gr-hovest-atb** [comment]
> Take a look at #172. Is that a duplicate?

They are related, but I would not consider it a duplicate. #172 seems to be about private profiles for the config server. This is about the "general start-up of CoatRack".
