### ISSUE TITLE
Generated gateway includes incorrect configuration

### ISSUE THREAD

**Issue by ChristophBaierATB** [coatrack/coatrack#186]
Follow-up issue of merging #152. Happened when testing `dev.coatrack.eu`.

Running a Gateway throws following exception:

<img width="955" alt="Screenshot 2022-03-10 124615" src="https://user-images.githubusercontent.com/70953785/157655832-f81ca6fc-bcb1-421e-a0ee-1330d83341b0.png">

As pointed out by the logs, the Gateway did receive the wrong Web Apllication URL `localhost:8080` instead of `dev.coatrack.eu`.

**Comment by gr-hovest-atb** [comment]
My assumption would be that the following parameter is responsible:
![image](https://user-images.githubusercontent.com/6480551/157684783-4040e141-2cd7-4d9a-b42d-f64663553eac.png)

This should be overwritten in the runtime config for `dev.coatrack.eu`

**Comment by ChristophBaierATB** [comment]
It is highly probably that this is the cause of the bug. Because the Web Application can't connect to the Bitbucket server (actual issue), no Gateway config is provided (follow-up issue).

<img width="969" alt="screenshot_2022-03-15_112745" src="https://user-images.githubusercontent.com/70953785/158798557-cb892088-5869-4519-a7a4-606807d1c286.png">
