### ISSUE TITLE
Calls registered by Gateway appear "one day earlier" in Admin statistics

### ISSUE THREAD

**Issue by gr-hovest-atb** [coatrack/coatrack#237]
# Observed problem

**Please note**: This happens *if and only if* Gateway and Admin are running on machines with different timezones. It was observed when using the dockerized Coatrack version:
* CoatRack Admin was running in a container set to GMT timezone
* CoatRack Gateway was running on a machine with timezone set to GMT+2 (CEST).

The observed problem is: 

* Calls to the CoatRack Gateway are done **today**
* In the reports in CoatRack Admin, those calls show up (only) if we look at the report from **yesterday**

# Reason

After some investigation, the reason is as follows (in this example, "today" is the 13 October 2022):

* the Coatrack Gateway registers the call and stores today's date with the call, which is in this example: `2022-10-13` (no time information is stored)
* when sending to CoatRack Admin, this date of `2022-10-13` is encoded by the Gateway as `java.util.Date` with time set to "midnight", i.e. in this example `2022-10-13 00:00:00 CEST` 
* when it arrives at CoatRack Admin, this date is interpreted according to the Admin's timezone, which is GMT, so it becomes: `2022-10-12 22:00:00 GMT` 
* then it is stored in Admin's database without any time information, so it becomes `2022-10-12` in Admin`s DB

What the current implementation actually intended in the first place was that the local date of the Gateway would be relevant, this is why we store it without time or timezone information. But the problem is that the actual transfer between Gateway and Admin adds time(zone) information which is afterwards removed again.  

# To be discussed: 

* Does it make sense to change the related field in the CoatRack API from `java.util.Date` to `java.time.LocalDate`, so that the transfer between Gateway and Admin does not include timezone implications? What are the implications of changing the API that way?
* Besides, on a more general level: Who should "decide" about the date of the call? The timezone of the Gateway (imagine the Gateway is also dockerized and thus uses a different timezone)? The timezone of Admin?
* Or should we actually store the time(zone) info in the Admin database, not just the date? Then the display in the report would be adjusted to Admin timezone.

**Comment by ChristophBaierATB** [comment]
If we change the time, we should directly use `ZonedDateTime` instead of .

Quick-Fix:
* As a first step we would apply that change in the Proxy. We expect the feature to work properly if we not test it between 0:00 am and 2:00 am.

Long Term Solutions:
* We apply the same change to Admins logic, but we should be careful since it will affect database scheme and could produce a lot of rows (one for each request) if implemented improperly.
* Maybe its worth the time and effort to replace the current metric mechanism with Micrometer.

**Comment by gr-hovest-atb** [comment]
As discussed today, the short term solution for the problem would be as follows:

- Gateway should not set the time to "midnight", but instead send its actual current time to Admin
- Admin would then map the time to its own timezone, which could still lead to "changing to the previous day", but only during the hours when there are actually different days (i.e. in the example above, Admin would only store the previous day "between midnight and 2 am Gateway time - GMT+2" which translates to "between 10pm and midnight Admin time - GMT")

**Comment by ChristophBaierATB** [comment]
I found the problem. The critical snippet is in the `proxy? module in the `MetricsCounter` class. 
```java
    private String createCounterIdFromMetric(TemporaryMetricsAggregation tma) {
        StringJoiner stringJoiner = new StringJoiner(SEPARATOR);
        stringJoiner.add(PREFIX)
                .add(tma.getServiceApiName())
                .add(tma.getRequestMethod())
                .add(tma.getApiKeyValue())
                .add(tma.getMetricType().toString())
                .add(String.valueOf(tma.getHttpResponseCode()))
                .add(LocalDate.now().toString()) # <-- here is the problem
                .add(tma.getPath());
        return stringJoiner.toString();
    }
```

The logic above was introduced during the Spring Boot version update to keep the metrics mechanism just working. The problem here is that We used to have a `Date` here, which is agnostic about time zones in contrast to the used `LocalDate`. The fix is to simply replace that `LocalDate` by a `Date` string:
```java
.add(Date.valueOf(LocalDate.now()).toString())
```

**Comment by ChristophBaierATB** [comment]
The follow-up issue for the long-term solution is #118.
