### ISSUE TITLE
Building via "mvn clean install" requires config server to run. If there is no config server available then it fails during test

### ISSUE THREAD

**Issue by BrunoSilvaATB** [coatrack/coatrack#25]
After checking out the project, a normal “mvn clean install” should not require a connection to the CoatRack config server. We should consider including a default config for the tests, so that building including “mvn test” can be done without config server.

**Comment by BrunoSilvaATB** [comment]
@gr-hovest-atb I have been working on this issue and found different alternatives to solve it:
- One that is working already (in my local) is by using an application-test.yml on local with the configuration wished (I used the default config on the config server), then the user just need to run on the console the command 
**mvn clean test -Dspring.profiles.active=test and uncomment the line with spring.cloud.config.enabled=false (added by me on the bootstrap.properties file)

- The other way (I am trying it now) is to connect a Maven Profile (this maven profile needed to be activated by default and have a properties to pass to the bootstrap.properties of Spring Boot), so that when the user inserts the command "mvn test",
Maven would activate the default profile and pass the parameter "test" to the Spring Boot profile activating it.

PS: For this to work, the Spring Cloud needs to be disabled ( spring.cloud.config.enabled=false  in bootstrap.properties), I already added this line to the bootstrap.properties

**Comment by gr-hovest-atb** [comment]
It seems like this was "implicitly fixed" by #158
