### ISSUE TITLE
Gateway should be able to run for a while without being able to call admin application

### ISSUE THREAD

**Issue by gr-hovest-atb** [coatrack/coatrack#73]
Right now, on every call to a gateway, the API key that was passed is checked "on the fly" by calling the admin application. However, in case the connection to the admin application is lost temporarily (e.g. because admin is down for maintenance), the gateway is not able to check the API key, therefore not allowing the call.

Suggested enhancement: the gateway should temporarily store valid API keys so that it can authorize incoming calls even if the admin application cannot be reached. However, it should regularly ask admin for an updated list of API keys in case one key would become invalid/deleted.

**Comment by gr-hovest-atb** [comment]
@Monezz, @perezdf, @BrunoSilvaATB : we should have a discussion about the concept for this enhancement.

**Comment by gr-hovest-atb** [comment]
@Monezz @perezdf @BrunoSilvaATB here is a summary of our discussion, please check and improve as you see fit:

- the current mechanism of "the gateway checks all incoming API keys via a call to admin" should stay as it is for now
- in addition, to enable the gateway to work in case the connection to admin gets lost:
  - the gateway should call admin in a fixed time interval (e.g. every 5 minutes) to get an up-to-date list of API keys that are valid right now for the service APIs supported by this gateway
  - gateway will store this list of valid API keys locally (in-memory/non-persistent is sufficient for now)
  - a one-way hash function should be applied to the keys before local storage to prevent tampering
  - in case the connection to admin is lost, the gateway can use the local list of hashed API keys as a fallback mechanism to check incoming API keys
  - after a predefined time period without connection to admin (e.g. 1 hour or 1 day), the gateway should stop using the fallback mechanism and block all further incoming calls until the connection to admin is restored (as usually the API keys are still valid in this case, but just the connection to admin is lost, the gateway should not reply "403 Forbidden" to service API clients but a clear error message)

**Comment by BrunoSilvaATB** [comment]
**There could be a way to combine this with #83. 
This issue is higher priority than the previous defined issue.**

- A cronjob should be used with a sample with 5min, but this time should be configurable
- The API Key list should be one way Hashed
